services:
  db:
    image: mysql:5.7
    container_name: hotel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bluebirdhotel   
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: hotel_web
    restart: always
    ports:
      - "8080:80"    
    environment:
      - DB_HOST=db
      - DB_USER=hotel_user
      - DB_PASSWORD=hotel_password
      - DB_NAME=hotel_management
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
